# app.py
import streamlit as st

st.set_page_config(page_title="Pilotage plan 2026", layout="wide")
st.title(" 🎓 Accueil — Pilotage de la formation")

st.markdown("""
Bienvenue ! Utilisez le menu de gauche pour naviguer :

""")            
# - **💰 Budget global** : ...
# - **📊 Pilotage financier** : ...
# - **💸 Dépenses** : ...
# - **📉 Évolution coûts** : ...
# - **🧾 Détails budgetaires** : ...
# - **📈 Sessions** : ...
# - **🗓️ Planning sessions** : ...
# - **👥 Stagiaires / participants** : ...
# - **🚗 Déplacements** : ...
# - **🧳 Frais de mission** : ...
# - **📉 Indicateurs clés** : ...
# - **📈 Performance** : ...
# - **📚 Données / Référentiels** : ...
# - **🧩 Configurations / Paramètres** : ...
# - **🧮 Statistiques** : ...
# - **🗂️ Archivage / Historique** : ...
# - **🔧 Administration** : ...

